# Generated by Django 4.2.5 on 2024-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0003_alter_product_image_alter_productsize_product_and_more'),
        ('like', '0003_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='liked_by', through='like.Like', to='moderno.product'),
        ),
    ]
