# Generated by Django 5.0.2 on 2024-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='images/default_user.png', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
