# Generated by Django 4.2.5 on 2024-05-19 11:20

from django.db import migrations, models
import django.db.models.deletion
import moderno.models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to=moderno.models.product_image_directory_path, verbose_name='Фото товара'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='moderno.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='moderno.size', verbose_name='Размер'),
        ),
    ]
