# Generated by Django 5.0.2 on 2024-04-26 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
    ]
