# Generated by Django 5.0.2 on 2024-05-06 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0003_alter_size_options_alter_productsize_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='moderno.product'),
        ),
    ]
