# Generated by Django 4.2.5 on 2024-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0003_alter_product_image_alter_productsize_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(default='', max_length=1000, verbose_name='Отзыв'),
        ),
    ]
