# Generated by Django 5.0.2 on 2024-04-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0004_remove_product_size_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='changes',
        ),
    ]
