# Generated by Django 5.0.2 on 2024-04-27 11:32

import moderno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0006_alter_product_image_alter_productimage_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.png', upload_to=moderno.models.product_image_directory_path, verbose_name='Фото'),
        ),
    ]
