# Generated by Django 5.0.2 on 2024-05-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0006_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
        migrations.AddField(
            model_name='size',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='moderno.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('S', 'Маленький'), ('M', 'Средний'), ('L', 'Большой')], max_length=1, verbose_name='Размер'),
        ),
        migrations.DeleteModel(
            name='ProductSize',
        ),
    ]
