# Generated by Django 5.0.2 on 2024-05-07 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0008_alter_size_options_remove_size_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='moderno.product'),
        ),
    ]
