# Generated by Django 5.0.2 on 2024-04-27 12:16

import moderno.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0011_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to=moderno.models.product_image_directory_path, verbose_name='Фото'),
        ),
    ]
