# Generated by Django 5.0.2 on 2024-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0014_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, default='Не выбрано', null=True, verbose_name='Отзыв'),
        ),
    ]
