# Generated by Django 5.0.2 on 2024-04-27 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0017_alter_review_rating_alter_review_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-create_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
