# Generated by Django 5.0.2 on 2024-04-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0018_alter_review_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, max_length='255', null=True, verbose_name='Отзыв'),
        ),
    ]
