# Generated by Django 5.0.2 on 2024-04-28 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderno', '0020_alter_review_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descr',
            new_name='description',
        ),
    ]
