# Generated by Django 5.0.2 on 2024-05-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='Лайк')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления лайка')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранные товары',
                'ordering': ('-created_timestamp',),
            },
        ),
    ]
