# Generated by Django 5.0.2 on 2024-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Избранное'),
        ),
    ]
